<a href="https://colab.research.google.com/github/SEJUNTONY/Data_Science_Class/blob/main/1020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
list1 = [1,2,3]
array = np.array(list1)

print(array.size)
print(array.dtype)
print(array[2])

3
int64
3


In [5]:
array1 = np.arange(4)
print(array1)

array2 = np.zeros((4,4),dtype=float)
print(array2)

array3 = np.ones((3,3), dtype=str)
print(array3)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [6]:
array4 = np.random.randint(0,10, (3,3))
print(array4)

[[0 3 9]
 [7 3 1]
 [8 3 3]]


In [7]:
array5 = np.random.normal(0,1,(3,3))
print(array5)

[[-0.05477982 -0.05379223  1.33007725]
 [ 0.72133396 -0.77233176 -1.205205  ]
 [-0.82915601 -1.77459316 -0.91813929]]


In [8]:
array6 = np.array([1,2,3])
array7 = np.array([4,5,6])
array8 = np.concatenate([array6, array7]) # 배열에 감싸서 넣어주기

print(array8)
print(array8.shape) #몇곱하기몇 데이터인지 알려줌(가로3*세로2여서 6)

[1 2 3 4 5 6]
(6,)


In [9]:
array9 = np.array([1,2,3,4])
array10 = array9.reshape((2,2)) #(3,1)은 안됨

print(array10)
print(array10.shape)

[[1 2]
 [3 4]]
(2, 2)


In [13]:
array11 = np.arange(4).reshape(1,4)
array12 = np.arange(8).reshape(2,4)
#np.arange(8)= 0부터 8개의 숫자 출력하겠다.

print(array11)
print(array12)

array13 = np.concatenate([array11, array12], axis=0)
#11은 (1,4)구조, 12는 (2,4)니까 axis=0 해줘야 함
print(array13)

[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


In [16]:
array14 = np.arange(8).reshape(2,4)
left, right = np.split(array14, [2], axis=1)

print(array14)
print(left.shape)
print(right.shape) #새로운 행렬 취급
print(right[1][1]) #1번째줄의 1번째 값, right[1][0]은 6

[[0 1 2 3]
 [4 5 6 7]]
(2, 2)
(2, 2)
7
